### Obtenir tots els clubs
GET https://protactics-api.onrender.com/clubes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidGlwbyI6ImNsdWIiLCJjb3JyZW8iOiJtb2xsZXRAZ21haWwuY29tIiwiaWF0IjoxNzQ3MzIwMjMyLCJleHAiOjE3NDc0MDY2MzJ9.WDvLFNffXMJUVo7D_Ik1mU3bB8C1tpVuYH9H-w9NRj8
Content-Type: application/json
