### ✅ Canviar contrasenya (usuari autenticat)
PUT https://protactics-api.onrender.com/password
Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsI…czN30.11TN9bOFYRW7YrX8EurHZXt62tUkFBjCM6pAHCxEo7I

{
    "contrasena_actual": "alan",
    "contrasena_nova": "alan123"
}

### ❌ Prova sense token (ha de donar error 401)
PUT https://protactics-api.onrender.com/password
Content-Type: application/json

{
    "contrasena_actual": "alan",
    "contrasena_nova": "alan123"
}

### ❌ Prova amb una contrasenya incorrecta (ha de donar error 401)
PUT https://protactics-api.onrender.com/password
Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsI…czN30.11TN9bOFYRW7YrX8EurHZXt62tUkFBjCM6pAHCxEo7I

{
    "contrasena_actual": "incorrecta",
    "contrasena_nova": "alan123"
}

### ❌ Prova amb camps buits (ha de donar error 400)
PUT https://protactics-api.onrender.com/password
Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsI…czN30.11TN9bOFYRW7YrX8EurHZXt62tUkFBjCM6pAHCxEo7I

{
    "contrasena_actual": "",
    "contrasena_nova": ""
}
