### Obtener todos los usuarios
GET https://protactics-api.onrender.com/usuarios

### Obtener un usuario por ID (ID 1 - AlanTeixido)
GET https://protactics-api.onrender.com/usuarios/1

### Obtener un usuario por ID (ID 2 - AdminProTactics)
GET https://protactics-api.onrender.com/usuarios/2

### Actualizar usuario (ID 1 - AlanTeixido)
PUT https://protactics-api.onrender.com/usuarios/1
Content-Type: application/json

{
  "nombre_usuario": "AlanTeixidoUpdated",
  "correo": "alan.teixido@example.com",
  "contrasena_hash": "NuevaPassword",
  "rol": "usuario"
}

### Actualizar usuario (ID 2 - AdminProTactics)
PUT https://protactics-api.onrender.com/usuarios/2
Content-Type: application/json

{
  "nombre_usuario": "AdminProTacticsUpdated",
  "correo": "admin@protactics.com",
  "contrasena_hash": "NuevaPasswordAdmin",
  "rol": "administrador"
}

### Eliminar usuario (ID 1 - AlanTeixido)
DELETE https://protactics-api.onrender.com/usuarios/1

### Eliminar usuario (ID 2 - AdminProTactics)
DELETE https://protactics-api.onrender.com/usuarios/2
