### ✅ Canviar contrasenya (usuari autenticat)
PUT https://protactics-api.onrender.com/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsIm5vbWJyZV91c3VhcmlvIjoiQWxhbiIsImNvcnJlbyI6InRlaXhpZG8uYWxhbkBnbWFpbC5jb20iLCJpYXQiOjE3MzkzNzgzMDEsImV4cCI6MTczOTQ2NDcwMX0.yYPjPbNjzSW4Gl5tQ6ZSQ6wSiDxNYPfFlYw7DX96ceM

{
    "contrasena_actual": "alan",
    "contrasena_nova": "alan123"
}

### ❌ Prova sense token (ha de donar error 401)
PUT https://protactics-api.onrender.com/password
Content-Type: application/json

{
    "contrasena_actual": "alan",
    "contrasena_nova": "alan123"
}

### ❌ Prova amb una contrasenya incorrecta (ha de donar error 401)
PUT https://protactics-api.onrender.com/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsIm5vbWJyZV91c3VhcmlvIjoiQWxhbiIsImNvcnJlbyI6InRlaXhpZG8uYWxhbkBnbWFpbC5jb20iLCJpYXQiOjE3MzkzNzgzMDEsImV4cCI6MTczOTQ2NDcwMX0.yYPjPbNjzSW4Gl5tQ6ZSQ6wSiDxNYPfFlYw7DX96ceM

{
    "contrasena_actual": "incorrecta",
    "contrasena_nova": "alan123"
}

### ❌ Prova amb camps buits (ha de donar error 400)
PUT https://protactics-api.onrender.com/password
Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsI…czN30.11TN9bOFYRW7YrX8EurHZXt62tUkFBjCM6pAHCxEo7I

{
    "contrasena_actual": "",
    "contrasena_nova": ""
}
