### ✅ Canviar contrasenya (usuari autenticat)
PUT https://protactics-api.onrender.com/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "contrasena_actual": "{{password}}",
    "contrasena_nova": "{{password}}"
}

### ❌ Prova sense token (ha de donar error 401)
PUT https://protactics-api.onrender.com/password
Content-Type: application/json

{
    "contrasena_actual": "{{password}}",
    "contrasena_nova": "{{password}}"
}

### ❌ Prova amb una contrasenya incorrecta (ha de donar error 401)
PUT https://protactics-api.onrender.com/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "contrasena_actual": "{{password}}",
    "contrasena_nova": "{{password}}"
}

### ❌ Prova amb camps buits (ha de donar error 400)
PUT https://protactics-api.onrender.com/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "contrasena_actual": "{{password}}",
    "contrasena_nova": "{{password}}"
}
